export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST'
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS'
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL'
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET'

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET'

export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST'
export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS'
export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL'
export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET'

export const PRODUCT_TOP_REQUEST = 'PRODUCT_TOP_REQUEST'
export const PRODUCT_TOP_SUCCESS = 'PRODUCT_TOP_SUCCESS'
export const PRODUCT_TOP_FAIL = 'PRODUCT_TOP_FAIL'

export const PRODUCT_ARMANI_REQUEST = 'PRODUCT_ARMANI_REQUEST'
export const PRODUCT_ARMANI_SUCCESS = 'PRODUCT_ARMANI_SUCCESS'
export const PRODUCT_ARMANI_FAIL = 'PRODUCT_ARMANI_FAIL'

export const PRODUCT_BALDININI_REQUEST = 'PRODUCT_BALDININI_REQUEST'
export const PRODUCT_BALDININI_SUCCESS = 'PRODUCT_BALDININI_SUCCESS'
export const PRODUCT_BALDININI_FAIL = 'PRODUCT_BALDININI_FAIL'

export const PRODUCT_BLUMARINE_REQUEST = 'PRODUCT_BLUMARINE_REQUEST'
export const PRODUCT_BLUMARINE_SUCCESS = 'PRODUCT_BLUMARINE_SUCCESS'
export const PRODUCT_BLUMARINE_FAIL = 'PRODUCT_BLUMARINE_FAIL'

export const PRODUCT_BURBERRY_REQUEST = 'PRODUCT_BURBERRY_REQUEST'
export const PRODUCT_BURBERRY_SUCCESS = 'PRODUCT_BURBERRY_SUCCESS'
export const PRODUCT_BURBERRY_FAIL = 'PRODUCT_BURBERRY_FAIL'

export const PRODUCT_BVLGARI_REQUEST = 'PRODUCT_BVLGARI_REQUEST'
export const PRODUCT_BVLGARI_SUCCESS = 'PRODUCT_BVLGARI_SUCCESS'
export const PRODUCT_BVLGARI_FAIL = 'PRODUCT_BVLGARI_FAIL'

export const PRODUCT_HERRERA_REQUEST = 'PRODUCT_HERRERA_REQUEST'
export const PRODUCT_HERRERA_SUCCESS = 'PRODUCT_HERRERA_SUCCESS'
export const PRODUCT_HERRERA_FAIL = 'PRODUCT_HERRERA_FAIL'

export const PRODUCT_CAVALLI_REQUEST = 'PRODUCT_CAVALLI_REQUEST'
export const PRODUCT_CAVALLI_SUCCESS = 'PRODUCT_CAVALLI_SUCCESS'
export const PRODUCT_CAVALLI_FAIL = 'PRODUCT_CAVALLI_FAIL'

export const PRODUCT_DIESEL_REQUEST = 'PRODUCT_DIESEL_REQUEST'
export const PRODUCT_DIESEL_SUCCESS = 'PRODUCT_DIESEL_SUCCESS'
export const PRODUCT_DIESEL_FAIL = 'PRODUCT_DIESEL_FAIL'

export const PRODUCT_DIOR_REQUEST = 'PRODUCT_DIOR_REQUEST'
export const PRODUCT_DIOR_SUCCESS = 'PRODUCT_DIOR_SUCCESS'
export const PRODUCT_DIOR_FAIL = 'PRODUCT_DIOR_FAIL'

export const PRODUCT_GABBANA_REQUEST = 'PRODUCT_GABBANA_REQUEST'
export const PRODUCT_GABBANA_SUCCESS = 'PRODUCT_GABBANA_SUCCESS'
export const PRODUCT_GABBANA_FAIL = 'PRODUCT_GABBANA_FAIL'

export const PRODUCT_ESCADA_REQUEST = 'PRODUCT_ESCADA_REQUEST'
export const PRODUCT_ESCADA_SUCCESS = 'PRODUCT_ESCADA_SUCCESS'
export const PRODUCT_ESCADA_FAIL = 'PRODUCT_ESCADA_FAIL'

export const PRODUCT_ART_REQUEST = 'PRODUCT_ART_REQUEST'
export const PRODUCT_ART_SUCCESS = 'PRODUCT_ART_SUCCESS'
export const PRODUCT_ART_FAIL = 'PRODUCT_ART_FAIL'

export const PRODUCT_FOSSIL_REQUEST = 'PRODUCT_FOSSIL_REQUEST'
export const PRODUCT_FOSSIL_SUCCESS = 'PRODUCT_FOSSIL_SUCCESS'
export const PRODUCT_FOSSIL_FAIL = 'PRODUCT_FOSSIL_FAIL'

export const PRODUCT_FURLA_REQUEST = 'PRODUCT_FURLA_REQUEST'
export const PRODUCT_FURLA_SUCCESS = 'PRODUCT_FURLA_SUCCESS'
export const PRODUCT_FURLA_FAIL = 'PRODUCT_FURLA_FAIL'

export const PRODUCT_GANT_REQUEST = 'PRODUCT_GANT_REQUEST'
export const PRODUCT_GANT_SUCCESS = 'PRODUCT_GANT_SUCCESS'
export const PRODUCT_GANT_FAIL = 'PRODUCT_GANT_FAIL'

export const PRODUCT_GUCCI_REQUEST = 'PRODUCT_GUCCI_REQUEST'
export const PRODUCT_GUCCI_SUCCESS = 'PRODUCT_GUCCI_SUCCESS'
export const PRODUCT_GUCCI_FAIL = 'PRODUCT_GUCCI_FAIL'

export const PRODUCT_BOSS_REQUEST = 'PRODUCT_BOSS_REQUEST'
export const PRODUCT_BOSS_SUCCESS = 'PRODUCT_BOSS_SUCCESS'
export const PRODUCT_BOSS_FAIL = 'PRODUCT_BOSS_FAIL'

export const PRODUCT_KORS_REQUEST = 'PRODUCT_KORS_REQUEST'
export const PRODUCT_KORS_SUCCESS = 'PRODUCT_KORS_SUCCESS'
export const PRODUCT_KORS_FAIL = 'PRODUCT_KORS_FAIL'

export const PRODUCT_LLOYD_REQUEST = 'PRODUCT_LLOYD_REQUEST'
export const PRODUCT_LLOYD_SUCCESS = 'PRODUCT_LLOYD_SUCCESS'
export const PRODUCT_LLOYD_FAIL = 'PRODUCT_LLOYD_FAIL'

export const PRODUCT_MARC_REQUEST = 'PRODUCT_MARC_REQUEST'
export const PRODUCT_MARC_SUCCESS = 'PRODUCT_MARC_SUCCESS'
export const PRODUCT_MARC_FAIL = 'PRODUCT_MARC_FAIL'

export const PRODUCT_MAX_REQUEST = 'PRODUCT_MAX_REQUEST'
export const PRODUCT_MAX_SUCCESS = 'PRODUCT_MAX_SUCCESS'
export const PRODUCT_MAX_FAIL = 'PRODUCT_MAX_FAIL'

export const PRODUCT_MOSCHINO_REQUEST = 'PRODUCT_MOSCHINO_REQUEST'
export const PRODUCT_MOSCHINO_SUCCESS = 'PRODUCT_MOSCHINO_SUCCESS'
export const PRODUCT_MOSCHINO_FAIL = 'PRODUCT_MOSCHINO_FAIL'

export const PRODUCT_PERSOL_REQUEST = 'PRODUCT_PERSOL_REQUEST'
export const PRODUCT_PERSOL_SUCCESS = 'PRODUCT_PERSOL_SUCCESS'
export const PRODUCT_PERSOL_FAIL = 'PRODUCT_PERSOL_FAIL'

export const PRODUCT_PRADA_REQUEST = 'PRODUCT_PRADA_REQUEST'
export const PRODUCT_PRADA_SUCCESS = 'PRODUCT_PRADA_SUCCESS'
export const PRODUCT_PRADA_FAIL = 'PRODUCT_PRADA_FAIL'

export const PRODUCT_PUMA_REQUEST = 'PRODUCT_PUMA_REQUEST'
export const PRODUCT_PUMA_SUCCESS = 'PRODUCT_PUMA_SUCCESS'
export const PRODUCT_PUMA_FAIL = 'PRODUCT_PUMA_FAIL'

export const PRODUCT_RAYBAN_REQUEST = 'PRODUCT_RAYBAN_REQUEST'
export const PRODUCT_RAYBAN_SUCCESS = 'PRODUCT_RAYBAN_SUCCESS'
export const PRODUCT_RAYBAN_FAIL = 'PRODUCT_RAYBAN_FAIL'

export const PRODUCT_RODENSTOCK_REQUEST = 'PRODUCT_RODENSTOCK_REQUEST'
export const PRODUCT_RODENSTOCK_SUCCESS = 'PRODUCT_RODENSTOCK_SUCCESS'
export const PRODUCT_RODENSTOCK_FAIL = 'PRODUCT_RODENSTOCK_FAIL'

export const PRODUCT_SWAROVSKI_REQUEST = 'PRODUCT_SWAROVSKI_REQUEST'
export const PRODUCT_SWAROVSKI_SUCCESS = 'PRODUCT_SWAROVSKI_SUCCESS'
export const PRODUCT_SWAROVSKI_FAIL = 'PRODUCT_SWAROVSKI_FAIL'

export const PRODUCT_TOM_REQUEST = 'PRODUCT_TOM_REQUEST'
export const PRODUCT_TOM_SUCCESS = 'PRODUCT_TOM_SUCCESS'
export const PRODUCT_TOM_FAIL = 'PRODUCT_TOM_FAIL'

export const PRODUCT_FORD_REQUEST = 'PRODUCT_FORD_REQUEST'
export const PRODUCT_FORD_SUCCESS = 'PRODUCT_FORD_SUCCESS'
export const PRODUCT_FORD_FAIL = 'PRODUCT_FORD_FAIL'

export const PRODUCT_VALENTINO_REQUEST = 'PRODUCT_VALENTINO_REQUEST'
export const PRODUCT_VALENTINO_SUCCESS = 'PRODUCT_VALENTINO_SUCCESS'
export const PRODUCT_VALENTINO_FAIL = 'PRODUCT_VALENTINO_FAIL'

export const PRODUCT_VICTORIA_REQUEST = 'PRODUCT_VICTORIA_REQUEST'
export const PRODUCT_VICTORIA_SUCCESS = 'PRODUCT_VICTORIA_SUCCESS'
export const PRODUCT_VICTORIA_FAIL = 'PRODUCT_VICTORIA_FAIL'

export const PRODUCT_VOGUE_REQUEST = 'PRODUCT_VOGUE_REQUEST'
export const PRODUCT_VOGUE_SUCCESS = 'PRODUCT_VOGUE_SUCCESS'
export const PRODUCT_VOGUE_FAIL = 'PRODUCT_VOGUE_FAIL'

export const PRODUCT_BRAND_REQUEST = 'PRODUCT_BRAND_REQUEST'
export const PRODUCT_BRAND_SUCCESS = 'PRODUCT_BRAND_SUCCESS'
export const PRODUCT_BRAND_FAIL = 'PRODUCT_BRAND_FAIL'



